# Generated by AI-assisted tooling — reviewed by <user>
import argparse
import sys
import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from university_sched.config.settings import Settings
from university_sched.models.base import Base
from university_sched.optimizer import Optimizer
from university_sched.reporting import ReportGenerator
from university_sched.constraint_engine import ConstraintEngine

def run_pipeline(args):
    # 1. Load Settings
    settings = Settings.load(args.config)
    
    # 2. Setup Database
    engine = create_engine(settings.database_url)
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()

    try:
        # 3. Initialize Optimizer
        optimizer = Optimizer(session, settings)
        
        # 4. Initial Assignment
        print("Starting Initial Assignment...")
        optimizer.run_initial_greedy_assignment()
        
        # 5. Optimization
        if not args.dry_run:
            print(f"Starting Optimization (iterations={args.iterations})...")
            optimizer.optimize_with_hill_climbing(iterations=args.iterations)
        
        # 6. Validation
        print("Validating constraints...")
        ConstraintEngine.validate_all(session, set(settings.exam_days))
        
        # 7. Generate Reports
        print(f"Generating reports in {args.outdir}...")
        reporter = ReportGenerator(session, out_dir=args.outdir)
        formats = []
        if args.csv: formats.append("csv")
        if args.json: formats.append("json")
        if not formats: formats = ["csv"] # Default
        
        reporter.generate_all(formats=formats)
        
        # Save decision log
        optimizer.decision_log.save(os.path.join(args.outdir, "decision_log.json"))
        
        print("Done.")

    finally:
        session.close()

def main():
    parser = argparse.ArgumentParser(description="Exam Scheduling Pipeline")
    parser.add_argument("--config", default="config.yml", help="Path to YAML config")
    parser.add_argument("--outdir", default="./reports", help="Output directory for reports")
    parser.add_argument("--iterations", type=int, default=100, help="Optimization iterations")
    parser.add_argument("--dry-run", action="store_true", help="Perform initial placement only")
    parser.add_argument("--csv", action="store_true", help="Generate CSV reports")
    parser.add_argument("--json", action="store_true", help="Generate JSON reports")
    
    args = parser.parse_args()
    
    try:
        run_pipeline(args)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
