# Generated by AI-assisted tooling — reviewed by <user>
from typing import List, Set, Tuple, Optional
from datetime import date, time
from sqlalchemy.orm import Session
from university_sched.models.schema import Offering, Room, OfferingBlock, Course
from university_sched.exceptions import ConstraintViolationError

class ConstraintEngine:
    """
    Enforces hard constraints for the exam schedule.
    Functions should be deterministic and raise ConstraintViolationError on failure.
    """

    @staticmethod
    def validate_exam_days(offering: Offering, allowed_days: Set[date]) -> None:
        """Enforces the 5-Day Limit constraint."""
        if offering.exam_date and offering.exam_date not in allowed_days:
            # Handle NSTP (Saturday is allowed for NSTP)
            if offering.exam_date.weekday() != 5: # 5 is Saturday
                 raise ConstraintViolationError(
                     f"Offering {offering.offering_no} assigned date {offering.exam_date} which is outside the 5-day limit."
                 )

    @staticmethod
    def validate_room_capacity(offering: Offering, room: Room) -> None:
        """Enforces the Capacity constraint."""
        if offering.num_enrolled > room.room_capacity:
            raise ConstraintViolationError(
                f"Offering {offering.offering_no} (enrollment: {offering.num_enrolled}) "
                f"exceeds capacity of Room {room.room_id} (capacity: {room.room_capacity})."
            )

    @staticmethod
    def validate_major_room_ownership(offering: Offering, room: Room) -> None:
        """Enforces Major Course Room Ownership restriction."""
        if offering.course.is_major:
            if offering.course.dept_id != room.dept_id:
                raise ConstraintViolationError(
                    f"Major course offering {offering.offering_no} (Dept: {offering.course.dept_id}) "
                    f"assigned to Room {room.room_id} owned by Dept: {room.dept_id}."
                )

    @staticmethod
    def check_time_overlap(
        start1: time, end1: time, start2: time, end2: time
    ) -> bool:
        """Returns True if two time windows overlap."""
        return max(start1, start2) < min(end1, end2)

    @classmethod
    def validate_block_conflicts(cls, session: Session, offering: Offering) -> None:
        """
        Enforces Block Conflict (student conflict) constraint.
        No two offerings referencing the same (block_no, degprog_id) may overlap in time.
        """
        if not (offering.exam_date and offering.time_slot_start and offering.time_slot_end):
            return

        # Find all block identifiers associated with this offering
        blocks = offering.offering_blocks
        if not blocks:
            return

        for block in blocks:
            # Find other offerings sharing this same block (block_no + degprog_id)
            conflicting_offerings = (
                session.query(Offering)
                .join(OfferingBlock)
                .filter(OfferingBlock.block_no == block.block_no)
                .filter(OfferingBlock.degprog_id == block.degprog_id)
                .filter(Offering.offering_no != offering.offering_no)
                .filter(Offering.exam_date == offering.exam_date)
                .all()
            )

            for other in conflicting_offerings:
                if other.time_slot_start and other.time_slot_end:
                    if cls.check_time_overlap(
                        offering.time_slot_start, offering.time_slot_end, 
                        other.time_slot_start, other.time_slot_end
                    ):
                        raise ConstraintViolationError(
                            f"Offering {offering.offering_no} overlaps with {other.offering_no} "
                            f"for shared block group ({block.degprog_id}-{block.block_no})."
                        )

    @classmethod
    def validate_all(cls, session: Session, allowed_days: Set[date]) -> None:
        """Validates the entire schedule against all hard constraints."""
        # Filter out Grad courses as per rule
        offerings = session.query(Offering).join(Course).filter(Course.is_grad == False).all()
        for offering in offerings:
            if offering.exam_date:
                cls.validate_exam_days(offering, allowed_days)
                
                if offering.room:
                    cls.validate_room_capacity(offering, offering.room)
                    cls.validate_major_room_ownership(offering, offering.room)
                
                cls.validate_block_conflicts(session, offering)
