# Generated by AI-assisted tooling — reviewed by <user>
from typing import List, Set, Tuple, Optional
from datetime import date, time, datetime
from sqlalchemy.orm import Session
from university_sched.models.schema import Offering, Room, Block, Course
from university_sched.exceptions import ConstraintViolationError

class ConstraintEngine:
    """
    Enforces hard constraints for the exam schedule.
    Functions should be deterministic and raise ConstraintViolationError on failure.
    """

    @staticmethod
    def validate_exam_days(offering: Offering, allowed_days: Set[date]) -> None:
        """Enforces the 5-Day Limit constraint."""
        if offering.exam_date and offering.exam_date not in allowed_days:
            # Check if it's NSTP (Saturday is allowed for NSTP)
            # For simplicity, we assume allowed_days includes NSTP days if they are pre-seeded,
            # or we handle NSTP as an exception.
            # README says: "Scheduling domain is five consecutive exam days... The solver will only assign exam_date within this set."
            # "NSTP offerings are pre-seeded... Saturday slot... immovable."
            if offering.exam_date.weekday() != 5: # 5 is Saturday
                 raise ConstraintViolationError(
                     f"Offering {offering.offering_id} assigned date {offering.exam_date} which is outside the 5-day limit."
                 )

    @staticmethod
    def validate_room_capacity(offering: Offering, room: Room) -> None:
        """Enforces the Capacity constraint."""
        if offering.num_enrolled > room.room_capacity:
            raise ConstraintViolationError(
                f"Offering {offering.offering_id} (enrollment: {offering.num_enrolled}) "
                f"exceeds capacity of Room {room.room_id} (capacity: {room.room_capacity})."
            )

    @staticmethod
    def validate_major_room_ownership(offering: Offering, room: Room) -> None:
        """Enforces Major Course Room Ownership restriction."""
        if offering.course.is_major:
            if offering.course.dept_id != room.dept_id:
                raise ConstraintViolationError(
                    f"Major course offering {offering.offering_id} (Dept: {offering.course.dept_id}) "
                    f"assigned to Room {room.room_id} owned by Dept: {room.dept_id}."
                )

    @staticmethod
    def check_time_overlap(
        start1: time, end1: time, start2: time, end2: time
    ) -> bool:
        """Returns True if two time windows overlap."""
        # Convert to datetime for comparison if needed, or just direct time comparison
        return max(start1, start2) < min(end1, end2)

    @classmethod
    def validate_block_conflicts(cls, session: Session, offering: Offering) -> None:
        """
        Enforces Block Conflict (student conflict) constraint.
        No two offerings referencing the same block_id may overlap in time.
        """
        if not (offering.exam_date and offering.start_time and offering.end_time):
            return

        # Find all blocks associated with this offering
        block_ids = {b.block_id for b in offering.blocks}
        if not block_ids:
            return

        # Find other offerings in the same blocks at the same date
        conflicting_offerings = (
            session.query(Offering)
            .join(Block)
            .filter(Block.block_id.in_(block_ids))
            .filter(Offering.offering_id != offering.offering_id)
            .filter(Offering.exam_date == offering.exam_date)
            .all()
        )

        for other in conflicting_offerings:
            if other.start_time and other.end_time:
                if cls.check_time_overlap(
                    offering.start_time, offering.end_time, other.start_time, other.end_time
                ):
                    raise ConstraintViolationError(
                        f"Offering {offering.offering_id} overlaps with {other.offering_id} "
                        f"for shared block student groups."
                    )

    @classmethod
    def validate_all(cls, session: Session, allowed_days: Set[date]) -> None:
        """Validates the entire schedule against all hard constraints."""
        offerings = session.query(Offering).all()
        for offering in offerings:
            if offering.exam_date:
                cls.validate_exam_days(offering, allowed_days)
                
                if offering.room:
                    cls.validate_room_capacity(offering, offering.room)
                    cls.validate_major_room_ownership(offering, offering.room)
                
                cls.validate_block_conflicts(session, offering)