# Generated by AI-assisted tooling — reviewed by <user>
from typing import List, Dict, Any, Type, Optional
import pandas as pd
from sqlalchemy.orm import Session
from university_sched.models.schema import (
    Department, Course, Faculty, Room, DegreeProgram, Major, Offering, Block
)
from university_sched.exceptions import DataValidationError

class DataIngestor:
    """
    Handles loading, validating, and preprocessing data for the scheduler.
    Implements mandatory exclusions (e.g., Graduate Education).
    """

    def __init__(self, session: Session):
        self.session = session

    def load_departments(self, df: pd.DataFrame) -> None:
        """Loads departments and filters out Graduate Education."""
        for _, row in df.iterrows():
            if row["dept_name"] == "Graduate Education":
                continue # Skip Graduate Education
            
            dept = Department(
                dept_id=row["dept_id"],
                dept_name=row["dept_name"]
            )
            self.session.add(dept)
        self.session.flush()

    def load_courses(self, df: pd.DataFrame) -> None:
        """Loads courses, ensuring they belong to an existing department."""
        valid_dept_ids = {d.dept_id for d in self.session.query(Department).all()}
        for _, row in df.iterrows():
            if row["dept_id"] not in valid_dept_ids:
                continue # Skip if dept was filtered out (e.g., Graduate Education)
            
            course = Course(
                course_id=row["course_id"],
                dept_id=row["dept_id"],
                crs_desc=row["crs_desc"],
                is_major=bool(row.get("is_major", False))
            )
            self.session.add(course)
        self.session.flush()

    def load_faculty(self, df: pd.DataFrame) -> None:
        """Loads faculty members."""
        valid_dept_ids = {d.dept_id for d in self.session.query(Department).all()}
        for _, row in df.iterrows():
             if row["dept_id"] not in valid_dept_ids:
                continue
             
             faculty = Faculty(
                 faculty_id=row["faculty_id"],
                 dept_id=row["dept_id"],
                 faculty_name=row["faculty_name"]
             )
             self.session.add(faculty)
        self.session.flush()

    def load_rooms(self, df: pd.DataFrame) -> None:
        """Loads rooms."""
        valid_dept_ids = {d.dept_id for d in self.session.query(Department).all()}
        for _, row in df.iterrows():
            if row["dept_id"] not in valid_dept_ids:
                continue
            
            room = Room(
                room_id=row["room_id"],
                dept_id=row["dept_id"],
                room_capacity=row["room_capacity"]
            )
            self.session.add(room)
        self.session.flush()

    def load_offerings(self, df: pd.DataFrame) -> None:
        """Loads offerings, identifying fixed bookings (e.g., NSTP)."""
        valid_course_ids = {c.course_id for c in self.session.query(Course).all()}
        valid_faculty_ids = {f.faculty_id for f in self.session.query(Faculty).all()}
        
        for _, row in df.iterrows():
            if row["course_id"] not in valid_course_ids:
                continue # Course filtered out
            
            # Handle dates and times
            exam_date = pd.to_datetime(row["exam_date"]).date() if pd.notnull(row.get("exam_date")) else None
            start_time = pd.to_datetime(row["start_time"]).time() if pd.notnull(row.get("start_time")) else None
            end_time = pd.to_datetime(row["end_time"]).time() if pd.notnull(row.get("end_time")) else None

            offering = Offering(
                offering_id=row["offering_id"],
                course_id=row["course_id"],
                faculty_id=row["faculty_id"],
                room_id=row.get("room_id") if pd.notnull(row.get("room_id")) else None,
                num_enrolled=row["num_enrolled"],
                exam_date=exam_date,
                start_time=start_time,
                end_time=end_time
            )
            self.session.add(offering)
        self.session.flush()

    def load_blocks(self, df: pd.DataFrame) -> None:
        """Loads blocks, linking offerings to majors."""
        valid_offering_ids = {o.offering_id for o in self.session.query(Offering).all()}
        # Note: In a real scenario, we'd also validate major_id
        
        for _, row in df.iterrows():
            if row["offering_id"] not in valid_offering_ids:
                continue
            
            block = Block(
                block_id=row["block_id"],
                offering_id=row["offering_id"],
                major_id=row["major_id"],
                year_level=row["year_level"]
            )
            self.session.add(block)
        self.session.flush()

    def commit(self) -> None:
        self.session.commit()
