# Generated by AI-assisted tooling — reviewed by <user>

class SchedulerError(Exception):
    """Base class for all scheduler-related exceptions."""
    pass

class ConstraintViolationError(SchedulerError):
    """Raised when a hard constraint is violated during scheduling or validation."""
    pass

class DataValidationError(SchedulerError):
    """Raised when input data fails validation (e.g., missing fields, invalid types)."""
    pass

class InfeasibleScheduleError(SchedulerError):
    """Raised when a valid schedule cannot be found given the current constraints."""
    pass
