# Generated by AI-assisted tooling — reviewed by <user>
import json
import random
from typing import List, Dict, Any, Optional, Set, Tuple
from datetime import date, time
from sqlalchemy.orm import Session
from university_sched.models.schema import Offering, Room, Block, Course, Department
from university_sched.config.settings import Settings, TimeSlot
from university_sched.constraint_engine import ConstraintEngine
from university_sched.exceptions import ConstraintViolationError

class DecisionLog:
    """Helper to maintain an explainable audit trail of scheduling changes."""
    def __init__(self):
        self.logs: List[Dict[str, Any]] = []

    def log(self, offering_id: int, old_slot: Optional[Dict], new_slot: Dict, reason: str, cost_delta: float):
        self.logs.append({
            "offering_id": offering_id,
            "old_slot": old_slot,
            "new_slot": new_slot,
            "reason": reason,
            "cost_delta": cost_delta
        })

    def save(self, file_path: str = "decision_log.json"):
        with open(file_path, "w") as f:
            json.dump(self.logs, f, indent=2, default=str)

class Optimizer:
    """
    Implements the optimization engine for soft goals.
    Prioritizes Student Load Balancing and Major Course Distribution.
    """

    def __init__(self, session: Session, settings: Settings):
        self.session = session
        self.settings = settings
        self.decision_log = DecisionLog()

    def calculate_student_load_penalty(self) -> float:
        """
        Each block should ideally have 2 exams/day, maximum 3/day.
        w1*(deviation from 2 exams/day) + w2*(over-max-penalty)
        """
        penalty = 0.0
        w_balance = self.settings.optimization_weights.student_balance
        
        # Group offerings by block and day
        from sqlalchemy import func
        from university_sched.models.schema import Block
        
        # This is a bit complex for a single query, so we'll calculate it in Python
        block_exams = {} # (block_id, day) -> count
        
        offerings = self.session.query(Offering).filter(Offering.exam_date != None).all()
        for off in offerings:
            for block in off.blocks:
                key = (block.block_id, off.exam_date)
                block_exams[key] = block_exams.get(key, 0) + 1
        
        for count in block_exams.values():
            if count > 3:
                penalty += w_balance * 10.0 * (count - 3) # Heavy penalty for over 3
            elif count != 2:
                penalty += w_balance * 1.0 * abs(count - 2)
        
        return penalty

    def calculate_major_distribution_penalty(self) -> float:
        """Spread major offerings evenly across the 5 days."""
        penalty = 0.0
        w_dist = self.settings.optimization_weights.major_distribution
        
        day_counts = {day: 0 for day in self.settings.exam_days}
        major_offerings = (
            self.session.query(Offering)
            .join(Course)
            .filter(Course.is_major == True)
            .filter(Offering.exam_date != None)
            .all()
        )
        
        for off in major_offerings:
            day_counts[off.exam_date] += 1
            
        total_majors = len(major_offerings)
        if total_majors == 0:
            return 0.0
            
        target_per_day = total_majors / len(self.settings.exam_days)
        
        for count in day_counts.values():
            penalty += w_dist * (abs(count - target_per_day))
            
        return penalty

    def find_adjacent_room(self, room_id: int, required_capacity: int) -> Optional[int]:
        """Finds an adjacent room that can fit the required capacity."""
        from university_sched.models.schema import RoomAdjacency
        adj = (
            self.session.query(Room)
            .join(RoomAdjacency, RoomAdjacency.adjacent_room_id == Room.room_id)
            .filter(RoomAdjacency.room_id == room_id)
            .filter(Room.room_capacity >= required_capacity)
            .first()
        )
        return adj.room_id if adj else None

    def optimize_with_hill_climbing(self, iterations: int = 100):
        """
        Attempts to improve the schedule by swapping slots for random offerings.
        Only accepts moves that reduce the total cost and satisfy all hard constraints.
        """
        print(f"Starting optimization (Hill Climbing, {iterations} iterations)...")
        current_cost = self.get_total_cost()
        
        offerings = self.session.query(Offering).all()
        rooms = self.session.query(Room).all()
        
        for i in range(iterations):
            offering = random.choice(offerings)
            
            # Save old slot
            old_day = offering.exam_date
            old_slot_start = offering.start_time
            old_slot_end = offering.end_time
            old_room_id = offering.room_id
            
            # Pick a random new slot
            new_day = random.choice(self.settings.exam_days)
            new_slot = random.choice(self.settings.allowed_time_slots)
            new_room = random.choice(rooms)
            
            try:
                # Apply move
                offering.exam_date = new_day
                offering.start_time = new_slot.start
                offering.end_time = new_slot.end
                offering.room_id = new_room.room_id
                
                # Check hard constraints
                ConstraintEngine.validate_all(self.session, set(self.settings.exam_days))
                
                new_cost = self.get_total_cost()
                
                if new_cost < current_cost:
                    # Accept move
                    current_cost = new_cost
                    self.decision_log.log(
                        offering.offering_id,
                        {"date": old_day, "start": old_slot_start, "room": old_room_id},
                        {"date": new_day, "start": new_slot.start, "room": new_room.room_id},
                        f"Optimization iteration {i}",
                        new_cost - current_cost
                    )
                else:
                    # Reject move (no improvement)
                    raise ConstraintViolationError("No improvement") # Just to trigger revert
                    
            except ConstraintViolationError:
                # Revert move
                offering.exam_date = old_day
                offering.start_time = old_slot_start
                offering.end_time = old_slot_end
                offering.room_id = old_room_id

    def get_total_cost(self) -> float:
        """Calculates total weighted cost of the current schedule."""
        return (
            self.calculate_student_load_penalty() +
            self.calculate_major_distribution_penalty()
        )

    def assign_to_slot(self, offering: Offering, day: date, slot: TimeSlot, room: Room, reason: str):
        """
        Assigns an offering to a (date, time, room) slot and logs the action.
        """
        old_cost = self.get_total_cost()
        old_slot = {
            "date": str(offering.exam_date),
            "start": str(offering.start_time),
            "room": offering.room_id
        } if offering.exam_date else None

        # Apply assignment
        offering.exam_date = day
        offering.start_time = slot.start
        offering.end_time = slot.end
        offering.room_id = room.room_id
        
        new_cost = self.get_total_cost()
        new_slot = {
            "date": str(day),
            "start": str(slot.start),
            "room": room.room_id
        }
        
        self.decision_log.log(
            offering.offering_id, 
            old_slot, 
            new_slot, 
            reason, 
            new_cost - old_cost
        )

    def run_initial_greedy_assignment(self):
        """
        Performs an initial greedy placement of all offerings.
        Obeys all hard constraints.
        """
        # 1. Get all offerings to be scheduled (filtered by Graduate Education exclusion already)
        offerings = self.session.query(Offering).filter(Offering.exam_date == None).all()
        rooms = self.session.query(Room).all()
        
        # Sort offerings: majors first, then by enrollment (decreasing)
        offerings.sort(key=lambda o: (o.course.is_major, o.num_enrolled), reverse=True)

        for offering in offerings:
            placed = False
            # Try to find a valid slot
            for day in self.settings.exam_days:
                for slot in self.settings.allowed_time_slots:
                    for room in rooms:
                        try:
                            # Tentative assignment for validation
                            offering.exam_date = day
                            offering.start_time = slot.start
                            offering.end_time = slot.end
                            
                            ConstraintEngine.validate_room_capacity(offering, room)
                            ConstraintEngine.validate_major_room_ownership(offering, room)
                            ConstraintEngine.validate_block_conflicts(self.session, offering)
                            
                            # If we get here, it's valid
                            self.assign_to_slot(offering, day, slot, room, "Initial greedy placement")
                            placed = True
                            break
                        except ConstraintViolationError:
                            # Revert tentative fields for next try
                            offering.exam_date = None
                            offering.start_time = None
                            continue
                    if placed: break
                if placed: break
            
            if not placed:
                # Flag as infeasible if we can't place a single offering
                # In a real solver, we'd backtrack or use a more robust search
                print(f"Warning: Could not place offering {offering.offering_id} in initial assignment.")
