# Generated by AI-assisted tooling — reviewed by <user>
import csv
import json
import os
from typing import List, Dict, Any
from datetime import datetime
from sqlalchemy.orm import Session
from university_sched.models.schema import Offering, Room, Faculty, Course

class ReportGenerator:
    """
    Generates CSV and JSON reports based on the scheduled offerings.
    Adheres to the column and sorting requirements in README.md.
    """

    def __init__(self, session: Session, out_dir: str = "./reports"):
        self.session = session
        self.out_dir = out_dir
        os.makedirs(self.out_dir, exist_ok=True)

    def _write_csv(self, filename: str, fieldnames: List[str], data: List[Dict]):
        path = os.path.join(self.out_dir, filename)
        with open(path, "w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(data)

    def _write_json(self, filename: str, data: Any):
        path = os.path.join(self.out_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, default=str)

    def generate_exam_schedule(self, formats: List[str] = ["csv"]):
        """
        Produces the 'exam_schedule.csv'.
        Columns: Offering No., Course No., Course Description, Date, Time, Faculty, Room.
        Sorting: Date (asc), Time (asc), Course No. (asc).
        """
        offerings = (
            self.session.query(Offering)
            .join(Course)
            .filter(Offering.exam_date != None)
            .order_by(Offering.exam_date, Offering.start_time, Course.course_id)
            .all()
        )

        report_data = []
        for o in offerings:
            report_data.append({
                "Offering No.": o.offering_id,
                "Course No.": o.course_id,
                "Course Description": o.course.crs_desc,
                "Date of Exam": o.exam_date.strftime("%Y-%m-%d"),
                "Time of Exam": f"{o.start_time.strftime('%H:%M')}-{o.end_time.strftime('%H:%M')}",
                "Faculty of Offering": o.faculty.faculty_name,
                "Room of Exam": o.room_id
            })

        if "csv" in formats:
            self._write_csv("exam_schedule.csv", list(report_data[0].keys()) if report_data else [], report_data)
        if "json" in formats:
            self._write_json("exam_schedule.json", report_data)

    def generate_timetable_by_room(self, formats: List[str] = ["csv"]):
        """
        Produces the 'timetable_by_room.csv'.
        Grouped by Room. Within Room: Date (asc), Time (asc), Offering No (asc).
        """
        offerings = (
            self.session.query(Offering)
            .filter(Offering.exam_date != None)
            .order_by(Offering.room_id, Offering.exam_date, Offering.start_time, Offering.offering_id)
            .all()
        )

        report_data = []
        for o in offerings:
            report_data.append({
                "Room": o.room_id,
                "Date": o.exam_date.strftime("%Y-%m-%d"),
                "Time": f"{o.start_time.strftime('%H:%M')}-{o.end_time.strftime('%H:%M')}",
                "Offering No.": o.offering_id,
                "Course No.": o.course_id,
                "Total # of Examinees": o.num_enrolled
            })

        if "csv" in formats:
            self._write_csv("timetable_by_room.csv", list(report_data[0].keys()) if report_data else [], report_data)

    def generate_faculty_load(self, formats: List[str] = ["csv"]):
        """
        Produces the 'faculty_load.csv'.
        Sorting: Faculty Name (asc), Date (asc), Time (asc).
        """
        offerings = (
            self.session.query(Offering)
            .join(Faculty)
            .filter(Offering.exam_date != None)
            .order_by(Faculty.faculty_name, Offering.exam_date, Offering.start_time)
            .all()
        )

        report_data = []
        for o in offerings:
            report_data.append({
                "Faculty Name": o.faculty.faculty_name,
                "Date": o.exam_date.strftime("%Y-%m-%d"),
                "Time": f"{o.start_time.strftime('%H:%M')}-{o.end_time.strftime('%H:%M')}",
                "Room": o.room_id,
                "Offering No.": o.offering_id,
                "Course No.": o.course_id
            })

        if "csv" in formats:
            self._write_csv("faculty_load.csv", list(report_data[0].keys()) if report_data else [], report_data)

    def generate_all(self, formats: List[str] = ["csv"]):
        self.generate_exam_schedule(formats)
        self.generate_timetable_by_room(formats)
        self.generate_faculty_load(formats)
