# Generated by AI-assisted tooling — reviewed by <user>
import pytest
from datetime import date, time
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from university_sched.models.base import Base
from university_sched.models.schema import (
    Department, Course, Offering, Room, Block
)
from university_sched.constraint_engine import ConstraintEngine
from university_sched.exceptions import ConstraintViolationError

@pytest.fixture
def db_session():
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()
    yield session
    session.close()

def test_room_capacity_constraint(db_session):
    room = Room(room_id=1, dept_id=1, room_capacity=30)
    offering = Offering(offering_id=1, course_id=1, faculty_id=1, num_enrolled=40)
    
    with pytest.raises(ConstraintViolationError, match="exceeds capacity"):
        ConstraintEngine.validate_room_capacity(offering, room)

def test_major_room_ownership_constraint(db_session):
    dept_cs = Department(dept_id=1, dept_name="CS")
    dept_bio = Department(dept_id=2, dept_name="Biology")
    db_session.add_all([dept_cs, dept_bio])
    db_session.flush()

    course = Course(course_id=1, dept_id=1, crs_desc="CS Major Course", is_major=True)
    room_bio = Room(room_id=2, dept_id=2, room_capacity=50)
    offering = Offering(offering_id=1, course=course, faculty_id=1, num_enrolled=20)

    with pytest.raises(ConstraintViolationError, match="Major course offering"):
        ConstraintEngine.validate_major_room_ownership(offering, room_bio)

def test_block_conflict_detection(db_session):
    # Setup data
    offering1 = Offering(
        offering_id=1, course_id=1, faculty_id=1, num_enrolled=20,
        exam_date=date(2026, 3, 23), start_time=time(9, 0), end_time=time(12, 0)
    )
    offering2 = Offering(
        offering_id=2, course_id=2, faculty_id=2, num_enrolled=20,
        exam_date=date(2026, 3, 23), start_time=time(11, 0), end_time=time(14, 0) # Overlap
    )
    
    block1 = Block(block_id=1, offering=offering1, major_id=1, year_level=1)
    block1_link_to_offering2 = Block(block_id=1, offering=offering2, major_id=1, year_level=1)
    
    db_session.add_all([offering1, offering2, block1, block1_link_to_offering2])
    db_session.flush()

    # offering1 blocks relationship should now have block_id=1
    with pytest.raises(ConstraintViolationError, match="overlaps"):
        ConstraintEngine.validate_block_conflicts(db_session, offering1)

def test_check_time_overlap():
    assert ConstraintEngine.check_time_overlap(time(9, 0), time(12, 0), time(11, 0), time(14, 0)) == True
    assert ConstraintEngine.check_time_overlap(time(9, 0), time(11, 0), time(11, 0), time(14, 0)) == False # Touching is not overlap
    assert ConstraintEngine.check_time_overlap(time(13, 0), time(16, 0), time(8, 0), time(11, 0)) == False
