# Generated by AI-assisted tooling — reviewed by <user>
import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from university_sched.models.base import Base
from university_sched.models.schema import Department, Course
from university_sched.config.settings import Settings

@pytest.fixture
def test_settings():
    # Create a temporary config or just use the class
    return Settings.load("config.yml")

@pytest.fixture
def db_session(test_settings):
    # Use SQLite in-memory for testing
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()
    yield session
    session.close()

def test_settings_load(test_settings):
    assert test_settings.room_adjacency_mode == "fallback"
    assert len(test_settings.exam_days) > 0

def test_database_models(db_session):
    # Create Department
    dept = Department(dept_name="Computer Science")
    db_session.add(dept)
    db_session.commit()
    
    assert dept.dept_id is not None
    
    # Create Course
    course = Course(dept_id=dept.dept_id, crs_desc="Intro to CS", is_major=True)
    db_session.add(course)
    db_session.commit()
    
    assert course.course_id is not None
    assert course.department.dept_name == "Computer Science"
