# Generated by AI-assisted tooling — reviewed by <user>
import pytest
from datetime import date, time
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from university_sched.models.base import Base
from university_sched.models.schema import (
    Department, Course, Offering, Room, Block, Faculty
)
from university_sched.optimizer import Optimizer
from university_sched.config.settings import Settings

@pytest.fixture
def db_session():
    engine = create_engine("sqlite:///:memory:")
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()
    yield session
    session.close()

@pytest.fixture
def settings():
    return Settings.load("config.yml")

def test_initial_assignment_and_optimization(db_session, settings):
    # Setup minimal data
    dept = Department(dept_id=1, dept_name="CS")
    room = Room(room_id=101, dept_id=1, room_capacity=50)
    faculty = Faculty(faculty_id=1, dept_id=1, faculty_name="Dr. Smith")
    course = Course(course_id=1001, dept_id=1, crs_desc="Intro CS", is_major=True)
    
    # Create 5 offerings for the same block (should be spread over days)
    offering_ids = [1, 2, 3, 4, 5]
    for oid in offering_ids:
        offering = Offering(
            offering_id=oid, course_id=1001, faculty_id=1, num_enrolled=20
        )
        db_session.add(offering)
        # Link to same block
        block = Block(block_id=99, offering=offering, major_id=1, year_level=1)
        db_session.add(block)

    db_session.add_all([dept, room, faculty, course])
    db_session.commit()

    optimizer = Optimizer(db_session, settings)
    
    # Run initial assignment
    optimizer.run_initial_greedy_assignment()
    
    # Check that all are assigned
    offerings = db_session.query(Offering).all()
    assert all(o.exam_date is not None for o in offerings)
    
    initial_cost = optimizer.get_total_cost()
    print(f"Initial cost: {initial_cost}")
    
    # Run optimization
    optimizer.optimize_with_hill_climbing(iterations=50)
    
    final_cost = optimizer.get_total_cost()
    print(f"Final cost: {final_cost}")
    
    assert final_cost <= initial_cost
    
    # Check decision log
    assert len(optimizer.decision_log.logs) > 0
