# Generated by AI-assisted tooling — reviewed by <user>
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from university_sched.models.base import Base
from university_sched.models.schema import (
    Department, Course, Room, Faculty, Offering, Block
)

def seed(engine):
    Session = sessionmaker(bind=engine)
    session = Session()
    
    # Depts
    cs = Department(dept_id=1, dept_name="Computer Science")
    bio = Department(dept_id=2, dept_name="Biology")
    session.add_all([cs, bio])
    session.commit()
    
    # Rooms
    r1 = Room(room_id=101, dept_id=1, room_capacity=30)
    r2 = Room(room_id=201, dept_id=2, room_capacity=50)
    session.add_all([r1, r2])
    
    # Faculty
    f1 = Faculty(faculty_id=1, dept_id=1, faculty_name="Alice")
    f2 = Faculty(faculty_id=2, dept_id=2, faculty_name="Bob")
    session.add_all([f1, f2])
    
    # Courses
    c1 = Course(course_id=101, dept_id=1, crs_desc="Programming 1", is_major=True)
    c2 = Course(course_id=201, dept_id=2, crs_desc="Genetics", is_major=False)
    session.add_all([c1, c2])
    session.commit()
    
    # Offerings
    o1 = Offering(offering_id=1, course_id=101, faculty_id=1, num_enrolled=25)
    o2 = Offering(offering_id=2, course_id=201, faculty_id=2, num_enrolled=40)
    session.add_all([o1, o2])
    
    # Blocks
    b1 = Block(block_id=1, offering=o1, major_id=1, year_level=1)
    b2 = Block(block_id=2, offering=o2, major_id=2, year_level=1)
    session.add_all([b1, b2])
    
    session.commit()
    session.close()

if __name__ == "__main__":
    engine = create_engine("sqlite:///university_sched.db")
    Base.metadata.create_all(engine)
    seed(engine)
