# Generated by AI-assisted tooling — reviewed by <user>
import os
import argparse
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from university_sched.data_ingest import DataIngestor
from university_sched.models.base import Base
from university_sched.config.settings import Settings

def seed_from_csv(csv_dir: str):
    """
    Seeds the database from CSV files in a directory.
    CSVs must be named correctly and contain the required columns.
    """
    # 1. Load Settings and Engine
    settings = Settings.load()
    engine = create_engine(settings.database_url)
    
    # Guidelines mandate explicit safety checks: confirm if user wants to overwrite?
    # For a seed script, we'll assume they want to ensure schema exists.
    Base.metadata.create_all(engine)
    
    # 2. Setup Session and Ingestor
    Session = sessionmaker(bind=engine)
    session = Session()
    ingestor = DataIngestor(session)

    # 3. Define Processing Order (Respects Foreign Keys)
    # List of (filename, loading_method)
    order = [
        ("departments.csv", ingestor.load_departments),
        ("degree_programs.csv", ingestor.load_degree_programs),
        ("majors.csv", ingestor.load_majors),
        ("faculty.csv", ingestor.load_faculty),
        ("rooms.csv", ingestor.load_rooms),
        ("room_adjacencies.csv", ingestor.load_room_adjacencies),
        ("courses.csv", ingestor.load_courses),
        ("offerings.csv", ingestor.load_offerings),
        ("blocks.csv", ingestor.load_blocks),
    ]

    print(f"Reading CSVs from: {csv_dir}")

    try:
        for filename, load_func in order:
            path = os.path.join(csv_dir, filename)
            if os.path.exists(path):
                print(f"  -> Loading {filename}...")
                df = pd.read_csv(path)
                load_func(df)
            else:
                print(f"  .. Skipping {filename} (not found)")

        # 4. Commit all changes
        ingestor.commit()
        print("\nSeeding complete.")

    except Exception as e:
        session.rollback()
        print(f"\nError during seeding: {e}")
        raise
    finally:
        session.close()

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed database from CSV files.")
    parser.add_argument("--csv-dir", default="./seed_data", help="Directory containing CSV files")
    args = parser.parse_args()
    
    seed_from_csv(args.csv_dir)
