# Generated by AI-assisted tooling — reviewed by <user>
from typing import Optional, List
from datetime import date, time
from sqlalchemy import String, Integer, Boolean, ForeignKey, Date, Time, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from university_sched.models.base import Base

class Department(Base):
    """
    Represents an academic department.
    Owner of courses, rooms, and degree programs.
    """
    __tablename__ = "departments"

    dept_id: Mapped[str] = mapped_column(String(10), primary_key=True) # e.g., 'DABE', 'DOE'
    dept_name: Mapped[str] = mapped_column(String(100), nullable=False)

    # Relationships
    courses: Mapped[List["Course"]] = relationship(back_populates="department")
    rooms: Mapped[List["Room"]] = relationship(back_populates="department")
    degree_programs: Mapped[List["DegreeProgram"]] = relationship(back_populates="department")
    faculty_members: Mapped[List["Faculty"]] = relationship(back_populates="department")

    def __repr__(self) -> str:
        return f"<Department(dept_id='{self.dept_id}', dept_name='{self.dept_name}')>"


class DegreeProgram(Base):
    """
    Represents a degree program.
    Linked to Departments.
    """
    __tablename__ = "degree_programs"

    degprog_id: Mapped[str] = mapped_column(String(20), primary_key=True) # e.g., 'BSABE', 'BSA'
    dept_id: Mapped[str] = mapped_column(ForeignKey("departments.dept_id"), nullable=True)
    degprog_name: Mapped[str] = mapped_column(String(150), nullable=True)

    # Relationships
    department: Mapped["Department"] = relationship(back_populates="degree_programs")
    offering_blocks: Mapped[List["OfferingBlock"]] = relationship(back_populates="degree_program")

    def __repr__(self) -> str:
        return f"<DegreeProgram(degprog_id='{self.degprog_id}', name='{self.degprog_name}')>"


class Faculty(Base):
    """
    Represents a faculty member.
    """
    __tablename__ = "faculty"

    faculty_id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    faculty_name: Mapped[str] = mapped_column(String(150), nullable=False)
    dept_id: Mapped[str] = mapped_column(ForeignKey("departments.dept_id"), nullable=True)

    # Relationships
    department: Mapped["Department"] = relationship(back_populates="faculty_members")
    offerings: Mapped[List["Offering"]] = relationship(back_populates="faculty")

    def __repr__(self) -> str:
        return f"<Faculty(faculty_id={self.faculty_id}, faculty_name='{self.faculty_name}')>"


class Course(Base):
    """
    Represents a course.
    """
    __tablename__ = "courses"

    course_code: Mapped[str] = mapped_column(String(20), primary_key=True) # e.g., 'ABEn 132'
    course_description: Mapped[str] = mapped_column(Text, nullable=False)
    dept_id: Mapped[str] = mapped_column(ForeignKey("departments.dept_id"), nullable=True)
    is_major: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    is_grad: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Relationships
    department: Mapped["Department"] = relationship(back_populates="courses")
    offerings: Mapped[List["Offering"]] = relationship(back_populates="course")

    def __repr__(self) -> str:
        return f"<Course(course_code='{self.course_code}', desc='{self.course_description}', is_major={self.is_major})>"


class Room(Base):
    """
    Represents an exam venue.
    """
    __tablename__ = "rooms"

    room_id: Mapped[str] = mapped_column(String(50), primary_key=True)
    dept_id: Mapped[str] = mapped_column(ForeignKey("departments.dept_id"), nullable=True)
    room_capacity: Mapped[int] = mapped_column(Integer, nullable=False)

    # Relationships
    department: Mapped["Department"] = relationship(back_populates="rooms")
    offerings: Mapped[List["Offering"]] = relationship(back_populates="room")
    
    # Adjacency relationship
    adjacent_rooms: Mapped[List["RoomAdjacency"]] = relationship(
        "RoomAdjacency",
        foreign_keys="[RoomAdjacency.room_id]",
        back_populates="room",
    )

    def __repr__(self) -> str:
        return f"<Room(room_id='{self.room_id}', capacity={self.room_capacity})>"


class RoomAdjacency(Base):
    """
    Mapping for room adjacency.
    """
    __tablename__ = "room_adjacency"

    room_id: Mapped[str] = mapped_column(ForeignKey("rooms.room_id"), primary_key=True)
    adjacent_room_id: Mapped[str] = mapped_column(ForeignKey("rooms.room_id"), primary_key=True)

    room: Mapped["Room"] = relationship("Room", foreign_keys=[room_id], back_populates="adjacent_rooms")
    adjacent_room: Mapped["Room"] = relationship("Room", foreign_keys=[adjacent_room_id])

    def __repr__(self) -> str:
        return f"<RoomAdjacency(room_id='{self.room_id}', adjacent_room_id='{self.adjacent_room_id}')>"


class Offering(Base):
    """
    Core schedulable unit.
    """
    __tablename__ = "offerings"

    offering_no: Mapped[str] = mapped_column(String(20), primary_key=True) # e.g., 'A117'
    course_code: Mapped[str] = mapped_column(ForeignKey("courses.course_code"), nullable=False)
    faculty_id: Mapped[Optional[int]] = mapped_column(ForeignKey("faculty.faculty_id"), nullable=True)
    num_enrolled: Mapped[int] = mapped_column(Integer, nullable=False)
    
    # Schedule fields (merged from exam_schedules in schema.txt for simplicity in app)
    room_id: Mapped[Optional[str]] = mapped_column(ForeignKey("rooms.room_id"), nullable=True)
    exam_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    time_slot_start: Mapped[Optional[time]] = mapped_column(Time, nullable=True)
    time_slot_end: Mapped[Optional[time]] = mapped_column(Time, nullable=True)

    # Relationships
    course: Mapped["Course"] = relationship(back_populates="offerings")
    faculty: Mapped[Optional["Faculty"]] = relationship(back_populates="offerings")
    room: Mapped[Optional["Room"]] = relationship(back_populates="offerings")
    offering_blocks: Mapped[List["OfferingBlock"]] = relationship(back_populates="offering")

    def __repr__(self) -> str:
        return f"<Offering(offering_no='{self.offering_no}', course_code='{self.course_code}', enrolled={self.num_enrolled})>"


class OfferingBlock(Base):
    """
    Handles the relationship between an Offering, Block Number, and Degree Program.
    """
    __tablename__ = "offering_blocks"

    offering_no: Mapped[str] = mapped_column(ForeignKey("offerings.offering_no"), primary_key=True)
    block_no: Mapped[str] = mapped_column(String(10), primary_key=True) # e.g., '38', '40', or 'N/A'
    degprog_id: Mapped[str] = mapped_column(ForeignKey("degree_programs.degprog_id"), primary_key=True)
    year_level: Mapped[int] = mapped_column(Integer, nullable=True) # e.g., 1, 2, 3, 4

    # Relationships
    offering: Mapped["Offering"] = relationship(back_populates="offering_blocks")
    degree_program: Mapped["DegreeProgram"] = relationship(back_populates="offering_blocks")

    def __repr__(self) -> str:
        return f"<OfferingBlock(offering_no='{self.offering_no}', block_no='{self.block_no}', degprog_id='{self.degprog_id}')>"
