# Generated by AI-assisted tooling — reviewed by <user>
from typing import Optional, List
from datetime import date, time
from sqlalchemy import String, Integer, Boolean, ForeignKey, Date, Time, CheckConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship
from university_sched.models.base import Base

class Department(Base):
    """
    Represents an academic department.
    Owner of courses, rooms, and degree programs.
    """
    __tablename__ = "department"

    dept_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    dept_name: Mapped[str] = mapped_column(String, nullable=False)

    # Relationships
    courses: Mapped[List["Course"]] = relationship(back_populates="department")
    rooms: Mapped[List["Room"]] = relationship(back_populates="department")
    degree_programs: Mapped[List["DegreeProgram"]] = relationship(back_populates="department")
    faculty_members: Mapped[List["Faculty"]] = relationship(back_populates="department")

    def __repr__(self) -> str:
        return f"<Department(dept_id={self.dept_id}, dept_name='{self.dept_name}')>"


class Faculty(Base):
    """
    Represents a faculty member.
    Assigned to Offerings; used for Faculty Load reports.
    """
    __tablename__ = "faculty"

    faculty_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    dept_id: Mapped[int] = mapped_column(ForeignKey("department.dept_id"), nullable=False)
    faculty_name: Mapped[str] = mapped_column(String, nullable=False)

    # Relationships
    department: Mapped["Department"] = relationship(back_populates="faculty_members")
    offerings: Mapped[List["Offering"]] = relationship(back_populates="faculty")

    def __repr__(self) -> str:
        return f"<Faculty(faculty_id={self.faculty_id}, faculty_name='{self.faculty_name}')>"


class Room(Base):
    """
    Represents an exam venue.
    dept_id used for is_major room restriction. room_capacity is a hard constraint.
    """
    __tablename__ = "room"

    room_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    dept_id: Mapped[int] = mapped_column(ForeignKey("department.dept_id"), nullable=False)
    room_capacity: Mapped[int] = mapped_column(Integer, nullable=False)

    # Relationships
    department: Mapped["Department"] = relationship(back_populates="rooms")
    offerings: Mapped[List["Offering"]] = relationship(back_populates="room")
    
    # Adjacency relationship (managed via RoomAdjacency table)
    adjacent_rooms: Mapped[List["RoomAdjacency"]] = relationship(
        "RoomAdjacency",
        foreign_keys="[RoomAdjacency.room_id]",
        back_populates="room",
    )

    def __repr__(self) -> str:
        return f"<Room(room_id={self.room_id}, capacity={self.room_capacity})>"


class RoomAdjacency(Base):
    """
    Mapping for room adjacency.
    """
    __tablename__ = "room_adjacency"

    room_id: Mapped[int] = mapped_column(ForeignKey("room.room_id"), primary_key=True)
    adjacent_room_id: Mapped[int] = mapped_column(ForeignKey("room.room_id"), primary_key=True)

    room: Mapped["Room"] = relationship("Room", foreign_keys=[room_id], back_populates="adjacent_rooms")
    adjacent_room: Mapped["Room"] = relationship("Room", foreign_keys=[adjacent_room_id])

    def __repr__(self) -> str:
        return f"<RoomAdjacency(room_id={self.room_id}, adjacent_room_id={self.adjacent_room_id})>"


class DegreeProgram(Base):
    """
    Represents a degree program.
    Metadata; used by stakeholders.
    """
    __tablename__ = "degree_program"

    degprog_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    dept_id: Mapped[int] = mapped_column(ForeignKey("department.dept_id"), nullable=False)
    degprog_name: Mapped[str] = mapped_column(String, nullable=False)

    # Relationships
    department: Mapped["Department"] = relationship(back_populates="degree_programs")
    majors: Mapped[List["Major"]] = relationship(back_populates="degree_program")

    def __repr__(self) -> str:
        return f"<DegreeProgram(degprog_id={self.degprog_id}, name='{self.degprog_name}')>"


class Major(Base):
    """
    Represents a major within a degree program.
    Used to classify Blocks.
    """
    __tablename__ = "major"

    major_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    degprog_id: Mapped[int] = mapped_column(ForeignKey("degree_program.degprog_id"), nullable=False)
    major_name: Mapped[str] = mapped_column(String, nullable=False)

    # Relationships
    degree_program: Mapped["DegreeProgram"] = relationship(back_populates="majors")
    blocks: Mapped[List["Block"]] = relationship(back_populates="major")

    def __repr__(self) -> str:
        return f"<Major(major_id={self.major_id}, name='{self.major_name}')>"


class Course(Base):
    """
    Represents a course.
    is_major drives departmental room restriction and distribution heuristics.
    """
    __tablename__ = "course"

    course_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    dept_id: Mapped[int] = mapped_column(ForeignKey("department.dept_id"), nullable=False)
    crs_desc: Mapped[str] = mapped_column(String, nullable=False)
    is_major: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Relationships
    department: Mapped["Department"] = relationship(back_populates="courses")
    offerings: Mapped[List["Offering"]] = relationship(back_populates="course")

    def __repr__(self) -> str:
        return f"<Course(course_id={self.course_id}, desc='{self.crs_desc}', is_major={self.is_major})>"


class Offering(Base):
    """
    Core schedulable unit.
    exam_date, start_time, end_time are set by the scheduler.
    """
    __tablename__ = "offering"

    offering_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    course_id: Mapped[int] = mapped_column(ForeignKey("course.course_id"), nullable=False)
    faculty_id: Mapped[int] = mapped_column(ForeignKey("faculty.faculty_id"), nullable=False)
    room_id: Mapped[Optional[int]] = mapped_column(ForeignKey("room.room_id"), nullable=True) # Preferred room initially, then assigned room
    num_enrolled: Mapped[int] = mapped_column(Integer, nullable=False)
    
    # Schedule fields (nullable until scheduled)
    exam_date: Mapped[Optional[date]] = mapped_column(Date, nullable=True)
    start_time: Mapped[Optional[time]] = mapped_column(Time, nullable=True)
    end_time: Mapped[Optional[time]] = mapped_column(Time, nullable=True)

    # Relationships
    course: Mapped["Course"] = relationship(back_populates="offerings")
    faculty: Mapped["Faculty"] = relationship(back_populates="offerings")
    room: Mapped[Optional["Room"]] = relationship(back_populates="offerings")
    blocks: Mapped[List["Block"]] = relationship(back_populates="offering")

    def __repr__(self) -> str:
        return f"<Offering(offering_id={self.offering_id}, course_id={self.course_id}, enrolled={self.num_enrolled})>"


class Block(Base):
    """
    Represents a student group (collection of examinees for an offering).
    Block links drive student conflict constraints.
    """
    __tablename__ = "block"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    block_id: Mapped[int] = mapped_column(Integer, nullable=False)
    offering_id: Mapped[int] = mapped_column(ForeignKey("offering.offering_id"), nullable=False)
    major_id: Mapped[int] = mapped_column(ForeignKey("major.major_id"), nullable=False)
    year_level: Mapped[int] = mapped_column(Integer, nullable=False)

    # Relationships
    offering: Mapped["Offering"] = relationship(back_populates="blocks")
    major: Mapped["Major"] = relationship(back_populates="blocks")

    def __repr__(self) -> str:
        return f"<Block(block_id={self.block_id}, offering_id={self.offering_id}, year={self.year_level})>"
