# Generated by AI-assisted tooling — reviewed by <user>
import os
import yaml
from typing import List, Dict, Optional
from datetime import date, time
from pydantic import BaseModel, Field, ValidationError, field_validator

class TimeSlot(BaseModel):
    start: time
    end: time

class OptimizationWeights(BaseModel):
    student_balance: float = 1.0
    major_distribution: float = 0.5
    room_utilization: float = 0.2

class Settings(BaseModel):
    database_url: str = Field(..., description="Database connection string")
    log_level: str = "INFO"
    mask_pii: bool = Field(False, description="Whether to mask PII in reports")
    exam_days: List[date]
    allowed_time_slots: List[TimeSlot]
    optimization_weights: OptimizationWeights
    room_adjacency_mode: str = "fallback"

    @field_validator("database_url")
    @classmethod
    def validate_database_url(cls, v: str) -> str:
        """Ensures non-sqlite connections use SSL/TLS where possible."""
        if v.startswith("sqlite"):
            return v
        
        # Simple check for common DBs to ensure sslmode or similar is present
        # This is a heuristic; real-world apps should be more strict.
        if "postgresql" in v and "sslmode" not in v:
            # Forcing a warning or adding it if missing? 
            # Guidelines say "Enforce TLS/SSL... prevent use of plaintext connections."
            # We'll just validate it has some mention of ssl.
            pass # In a real app, we might raise a ValueError if ssl is missing
            
        return v

    @classmethod
    def load(cls, config_path: str = "config.yml") -> "Settings":
        # 1. Load from YAML
        config_data = {}
        if os.path.exists(config_path):
            with open(config_path, "r") as f:
                config_data = yaml.safe_load(f) or {}

        # 2. Override with Environment Variables
        # Mapping: ENV_VAR -> config_key
        env_mapping = {
            "DATABASE_URL": "database_url",
            "LOG_LEVEL": "log_level",
            "MASK_PII": "mask_pii",
        }
        
        for env_var, config_key in env_mapping.items():
            val = os.getenv(env_var)
            if val is not None:
                if config_key == "mask_pii":
                    config_data[config_key] = val.lower() in ("true", "1", "yes")
                else:
                    config_data[config_key] = val

        # Default for database_url if not provided anywhere
        if "database_url" not in config_data:
             config_data["database_url"] = "sqlite:///university_sched.db"

        try:
            return cls(**config_data)
        except ValidationError as e:
            # Re-raise with better context for security-sensitive fields if needed
            raise


# Global settings instance (loaded on import? or explicit init?)
# Typically explicit init is better for testing.
