# Generated by AI-assisted tooling — reviewed by <user>
import os
import yaml
from typing import List, Dict, Optional
from datetime import date, time
from pydantic import BaseModel, Field, ValidationError

class TimeSlot(BaseModel):
    start: time
    end: time

class OptimizationWeights(BaseModel):
    student_balance: float = 1.0
    major_distribution: float = 0.5
    room_utilization: float = 0.2

class Settings(BaseModel):
    database_url: str = Field(..., description="Database connection string")
    log_level: str = "INFO"
    exam_days: List[date]
    allowed_time_slots: List[TimeSlot]
    optimization_weights: OptimizationWeights
    room_adjacency_mode: str = "fallback"

    @classmethod
    def load(cls, config_path: str = "config.yml") -> "Settings":
        # 1. Load from YAML
        if os.path.exists(config_path):
            with open(config_path, "r") as f:
                config_data = yaml.safe_load(f) or {}
        else:
            config_data = {}

        # 2. Override with Environment Variables
        env_db_url = os.getenv("DATABASE_URL")
        if env_db_url:
            config_data["database_url"] = env_db_url
        
        env_log_level = os.getenv("LOG_LEVEL")
        if env_log_level:
            config_data["log_level"] = env_log_level

        # Ensure database_url is present (for development, default to sqlite memory if not provided?)
        # Guidelines say "Configure DATABASE_URL in environment (Postgres recommended)."
        # But for tests/local without env, we might want a fallback.
        if "database_url" not in config_data:
             # Fallback for local dev/testing if not set
             config_data["database_url"] = "sqlite:///university_sched.db"

        try:
            return cls(**config_data)
        except ValidationError as e:
            print("Configuration Error:")
            print(e)
            raise

# Global settings instance (loaded on import? or explicit init?)
# Typically explicit init is better for testing.
